[project]
name = "embeddingkittools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "coremltools>=8.1",
    "torch>=2.5.1",
    "transformers>=4.47.0",
]
